/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoyalMailRouteImport } from './routes/royal-mail'
import { Route as PacketaRouteImport } from './routes/packeta'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'

const RoyalMailRoute = RoyalMailRouteImport.update({
  id: '/royal-mail',
  path: '/royal-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketaRoute = PacketaRouteImport.update({
  id: '/packeta',
  path: '/packeta',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/admin/pages/',
  path: '/admin/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/admin/pages/$pageId',
  path: '/admin/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/packeta': typeof PacketaRoute
  '/royal-mail': typeof RoyalMailRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/packeta': typeof PacketaRoute
  '/royal-mail': typeof RoyalMailRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages': typeof AdminPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/packeta': typeof PacketaRoute
  '/royal-mail': typeof RoyalMailRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/contact'
    | '/integrations'
    | '/login'
    | '/orders'
    | '/packeta'
    | '/royal-mail'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/users'
    | '/api/$'
    | '/p/$slug'
    | '/admin/pages/$pageId'
    | '/admin/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/contact'
    | '/integrations'
    | '/login'
    | '/orders'
    | '/packeta'
    | '/royal-mail'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/users'
    | '/api/$'
    | '/p/$slug'
    | '/admin/pages/$pageId'
    | '/admin/pages'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/contact'
    | '/integrations'
    | '/login'
    | '/orders'
    | '/packeta'
    | '/royal-mail'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/users'
    | '/api/$'
    | '/p/$slug'
    | '/admin/pages/$pageId'
    | '/admin/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ContactRoute: typeof ContactRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PacketaRoute: typeof PacketaRoute
  RoyalMailRoute: typeof RoyalMailRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PSlugRoute: typeof PSlugRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/royal-mail': {
      id: '/royal-mail'
      path: '/royal-mail'
      fullPath: '/royal-mail'
      preLoaderRoute: typeof RoyalMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packeta': {
      id: '/packeta'
      path: '/packeta'
      fullPath: '/packeta'
      preLoaderRoute: typeof PacketaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/admin/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/admin/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ContactRoute: ContactRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PacketaRoute: PacketaRoute,
  RoyalMailRoute: RoyalMailRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiSplatRoute: ApiSplatRoute,
  PSlugRoute: PSlugRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
