/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as PurchaseOrdersSuppliersRouteImport } from './routes/purchase-orders.suppliers'
import { Route as PurchaseOrdersNewRouteImport } from './routes/purchase-orders.new'
import { Route as PurchaseOrdersIdRouteImport } from './routes/purchase-orders.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InventoryWooRouteImport } from './routes/inventory.woo'
import { Route as InventoryAuditRouteImport } from './routes/inventory.audit'
import { Route as IntegrationsShippingRouteImport } from './routes/integrations.shipping'
import { Route as IntegrationsChannelsRouteImport } from './routes/integrations.channels'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as IntegrationsShippingIndexRouteImport } from './routes/integrations.shipping.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as IntegrationsShippingRoyalMailRouteImport } from './routes/integrations.shipping.royal-mail'
import { Route as IntegrationsShippingPacketaRouteImport } from './routes/integrations.shipping.packeta'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchaseOrdersRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const PurchaseOrdersSuppliersRoute = PurchaseOrdersSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => PurchaseOrdersRoute,
} as any)
const PurchaseOrdersNewRoute = PurchaseOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchaseOrdersRoute,
} as any)
const PurchaseOrdersIdRoute = PurchaseOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchaseOrdersRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWooRoute = InventoryWooRouteImport.update({
  id: '/woo',
  path: '/woo',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryAuditRoute = InventoryAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InventoryRoute,
} as any)
const IntegrationsShippingRoute = IntegrationsShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsChannelsRoute = IntegrationsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => IntegrationsRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsShippingIndexRoute =
  IntegrationsShippingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IntegrationsShippingRoute,
  } as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/admin/pages/',
  path: '/admin/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsShippingRoyalMailRoute =
  IntegrationsShippingRoyalMailRouteImport.update({
    id: '/royal-mail',
    path: '/royal-mail',
    getParentRoute: () => IntegrationsShippingRoute,
  } as any)
const IntegrationsShippingPacketaRoute =
  IntegrationsShippingPacketaRouteImport.update({
    id: '/packeta',
    path: '/packeta',
    getParentRoute: () => IntegrationsShippingRoute,
  } as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/admin/pages/$pageId',
  path: '/admin/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/purchase-orders': typeof PurchaseOrdersRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/integrations/channels': typeof IntegrationsChannelsRoute
  '/integrations/shipping': typeof IntegrationsShippingRouteWithChildren
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/woo': typeof InventoryWooRoute
  '/p/$slug': typeof PSlugRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/purchase-orders/new': typeof PurchaseOrdersNewRoute
  '/purchase-orders/suppliers': typeof PurchaseOrdersSuppliersRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/integrations/shipping/packeta': typeof IntegrationsShippingPacketaRoute
  '/integrations/shipping/royal-mail': typeof IntegrationsShippingRoyalMailRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/integrations/shipping/': typeof IntegrationsShippingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/signup': typeof SignupRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/integrations/channels': typeof IntegrationsChannelsRoute
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/woo': typeof InventoryWooRoute
  '/p/$slug': typeof PSlugRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/purchase-orders/new': typeof PurchaseOrdersNewRoute
  '/purchase-orders/suppliers': typeof PurchaseOrdersSuppliersRoute
  '/inventory': typeof InventoryIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/integrations/shipping/packeta': typeof IntegrationsShippingPacketaRoute
  '/integrations/shipping/royal-mail': typeof IntegrationsShippingRoyalMailRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/integrations/shipping': typeof IntegrationsShippingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/purchase-orders': typeof PurchaseOrdersRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/integrations/channels': typeof IntegrationsChannelsRoute
  '/integrations/shipping': typeof IntegrationsShippingRouteWithChildren
  '/inventory/audit': typeof InventoryAuditRoute
  '/inventory/woo': typeof InventoryWooRoute
  '/p/$slug': typeof PSlugRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/purchase-orders/new': typeof PurchaseOrdersNewRoute
  '/purchase-orders/suppliers': typeof PurchaseOrdersSuppliersRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/integrations/shipping/packeta': typeof IntegrationsShippingPacketaRoute
  '/integrations/shipping/royal-mail': typeof IntegrationsShippingRoyalMailRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/integrations/shipping/': typeof IntegrationsShippingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/analytics'
    | '/contact'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/purchase-orders'
    | '/signup'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/users'
    | '/api/$'
    | '/integrations/channels'
    | '/integrations/shipping'
    | '/inventory/audit'
    | '/inventory/woo'
    | '/p/$slug'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/purchase-orders/suppliers'
    | '/inventory/'
    | '/purchase-orders/'
    | '/admin/pages/$pageId'
    | '/integrations/shipping/packeta'
    | '/integrations/shipping/royal-mail'
    | '/admin/pages/'
    | '/integrations/shipping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/analytics'
    | '/contact'
    | '/integrations'
    | '/login'
    | '/orders'
    | '/signup'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/users'
    | '/api/$'
    | '/integrations/channels'
    | '/inventory/audit'
    | '/inventory/woo'
    | '/p/$slug'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/purchase-orders/suppliers'
    | '/inventory'
    | '/purchase-orders'
    | '/admin/pages/$pageId'
    | '/integrations/shipping/packeta'
    | '/integrations/shipping/royal-mail'
    | '/admin/pages'
    | '/integrations/shipping'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/analytics'
    | '/contact'
    | '/integrations'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/purchase-orders'
    | '/signup'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/users'
    | '/api/$'
    | '/integrations/channels'
    | '/integrations/shipping'
    | '/inventory/audit'
    | '/inventory/woo'
    | '/p/$slug'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/purchase-orders/suppliers'
    | '/inventory/'
    | '/purchase-orders/'
    | '/admin/pages/$pageId'
    | '/integrations/shipping/packeta'
    | '/integrations/shipping/royal-mail'
    | '/admin/pages/'
    | '/integrations/shipping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRouteWithChildren
  SignupRoute: typeof SignupRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PSlugRoute: typeof PSlugRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof PurchaseOrdersRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/purchase-orders/suppliers': {
      id: '/purchase-orders/suppliers'
      path: '/suppliers'
      fullPath: '/purchase-orders/suppliers'
      preLoaderRoute: typeof PurchaseOrdersSuppliersRouteImport
      parentRoute: typeof PurchaseOrdersRoute
    }
    '/purchase-orders/new': {
      id: '/purchase-orders/new'
      path: '/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof PurchaseOrdersNewRouteImport
      parentRoute: typeof PurchaseOrdersRoute
    }
    '/purchase-orders/$id': {
      id: '/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof PurchaseOrdersIdRouteImport
      parentRoute: typeof PurchaseOrdersRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/woo': {
      id: '/inventory/woo'
      path: '/woo'
      fullPath: '/inventory/woo'
      preLoaderRoute: typeof InventoryWooRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/audit': {
      id: '/inventory/audit'
      path: '/audit'
      fullPath: '/inventory/audit'
      preLoaderRoute: typeof InventoryAuditRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/integrations/shipping': {
      id: '/integrations/shipping'
      path: '/shipping'
      fullPath: '/integrations/shipping'
      preLoaderRoute: typeof IntegrationsShippingRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/channels': {
      id: '/integrations/channels'
      path: '/channels'
      fullPath: '/integrations/channels'
      preLoaderRoute: typeof IntegrationsChannelsRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/shipping/': {
      id: '/integrations/shipping/'
      path: '/'
      fullPath: '/integrations/shipping/'
      preLoaderRoute: typeof IntegrationsShippingIndexRouteImport
      parentRoute: typeof IntegrationsShippingRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/admin/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/shipping/royal-mail': {
      id: '/integrations/shipping/royal-mail'
      path: '/royal-mail'
      fullPath: '/integrations/shipping/royal-mail'
      preLoaderRoute: typeof IntegrationsShippingRoyalMailRouteImport
      parentRoute: typeof IntegrationsShippingRoute
    }
    '/integrations/shipping/packeta': {
      id: '/integrations/shipping/packeta'
      path: '/packeta'
      fullPath: '/integrations/shipping/packeta'
      preLoaderRoute: typeof IntegrationsShippingPacketaRouteImport
      parentRoute: typeof IntegrationsShippingRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/admin/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IntegrationsShippingRouteChildren {
  IntegrationsShippingPacketaRoute: typeof IntegrationsShippingPacketaRoute
  IntegrationsShippingRoyalMailRoute: typeof IntegrationsShippingRoyalMailRoute
  IntegrationsShippingIndexRoute: typeof IntegrationsShippingIndexRoute
}

const IntegrationsShippingRouteChildren: IntegrationsShippingRouteChildren = {
  IntegrationsShippingPacketaRoute: IntegrationsShippingPacketaRoute,
  IntegrationsShippingRoyalMailRoute: IntegrationsShippingRoyalMailRoute,
  IntegrationsShippingIndexRoute: IntegrationsShippingIndexRoute,
}

const IntegrationsShippingRouteWithChildren =
  IntegrationsShippingRoute._addFileChildren(IntegrationsShippingRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsChannelsRoute: typeof IntegrationsChannelsRoute
  IntegrationsShippingRoute: typeof IntegrationsShippingRouteWithChildren
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsChannelsRoute: IntegrationsChannelsRoute,
  IntegrationsShippingRoute: IntegrationsShippingRouteWithChildren,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface InventoryRouteChildren {
  InventoryAuditRoute: typeof InventoryAuditRoute
  InventoryWooRoute: typeof InventoryWooRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryAuditRoute: InventoryAuditRoute,
  InventoryWooRoute: InventoryWooRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface PurchaseOrdersRouteChildren {
  PurchaseOrdersIdRoute: typeof PurchaseOrdersIdRoute
  PurchaseOrdersNewRoute: typeof PurchaseOrdersNewRoute
  PurchaseOrdersSuppliersRoute: typeof PurchaseOrdersSuppliersRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
}

const PurchaseOrdersRouteChildren: PurchaseOrdersRouteChildren = {
  PurchaseOrdersIdRoute: PurchaseOrdersIdRoute,
  PurchaseOrdersNewRoute: PurchaseOrdersNewRoute,
  PurchaseOrdersSuppliersRoute: PurchaseOrdersSuppliersRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
}

const PurchaseOrdersRouteWithChildren = PurchaseOrdersRoute._addFileChildren(
  PurchaseOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PurchaseOrdersRoute: PurchaseOrdersRouteWithChildren,
  SignupRoute: SignupRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiSplatRoute: ApiSplatRoute,
  PSlugRoute: PSlugRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
